# (실습) 어레이 인덱싱

**주의사항**

- `None`은 적절한 표현식으로 대체한다.
- `Pass`는 적절한 명령문으로 대체한다.

In [2]:
import numpy as np

## 인덱싱과 슬라이싱

**문제 1**

변수 `Z`가 크기가 10인 1차원 어레이를 가리키도록 하라.
단, 1차원 어레이의 다섯 번쨰 값(4번 인덱스)은 1이고 나머지는 0이어야 한다.
또한 `np.zeros()` 함수와 어레이 인덱싱을 반드시 이용한다.

In [24]:
Z = np.zeros(shape=10, dtype = int)
Z[4] = 1
print(Z)

[0 0 0 0 1 0 0 0 0 0]


아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])).all()

**문제 2**

변수 `Z`가 0에서 49까지의 정수로 구성된 1차원 어레이를 가리키도록 하라.
단, 내림차순으로 정렬되어야 하며 이를 위해 어레이 슬라이싱을 반드시 이용한다.
또한 `sort()` 메서드는 사용하지 않는다.

In [33]:
Z = np.arange(0,50)
Z = np.argsort(Z)[::-1]
print(Z)
pass

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
                       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
                       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])).all()

**문제 3**

변수 `Z`가 아래와 같은 (8,8) 모양의 2차원 어레이를 가리키도록 하라.
단, `np.zeros()` 함수와 어레이 슬라이싱을 이용한다.

```
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [38]:

Z = np.zeros(shape=8, dtype = int)
print(Z)
pass

[0 0 0 0 0 0 0 0]


아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[0, 1, 0, 1, 0, 1, 0, 1],
                       [1, 0, 1, 0, 1, 0, 1, 0],
                       [0, 1, 0, 1, 0, 1, 0, 1],
                       [1, 0, 1, 0, 1, 0, 1, 0],
                       [0, 1, 0, 1, 0, 1, 0, 1],
                       [1, 0, 1, 0, 1, 0, 1, 0],
                       [0, 1, 0, 1, 0, 1, 0, 1],
                       [1, 0, 1, 0, 1, 0, 1, 0]])).all()

**문제 4**

변수 `Z`가 아래와 같은 (10,10) 모양의 2차원 어레이를 가리키도록 하라.
단, `np.ones()` 함수와 어레이 슬라이싱을 반드시 이용한다.

```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```

In [ ]:
Z = None
pass

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z  == np.array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
                        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
                        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
                        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
                        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
                        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
                        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
                        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
                        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
                        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])).all()

**문제 5**

(1) 변수 `Z`가 아래와 같은 (7,7) 모양의 2차원 어레이를 가리키도록 하라.
단, `np.ones()` 함수, `np.pad()` 함수, 어레이 슬라이싱을 반드시 이용한다.

```
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
```

In [ ]:
Z = None
Z = None

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[0., 0., 0., 0., 0., 0., 0.],
                        [0., 1., 1., 1., 1., 1., 0.],
                        [0., 1., 1., 1., 1., 1., 0.],
                        [0., 1., 1., 1., 1., 1., 0.],
                        [0., 1., 1., 1., 1., 1., 0.],
                        [0., 1., 1., 1., 1., 1., 0.],
                        [0., 0., 0., 0., 0., 0., 0.]])).all

(2) 이번에는 인덱싱과 슬라이싱만을 이용하여 동일한 어레이를 생성하라.

In [ ]:
# 이것도 같은 동작
pass
pass

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([[0., 0., 0., 0., 0., 0., 0.],
                        [0., 1., 1., 1., 1., 1., 0.],
                        [0., 1., 1., 1., 1., 1., 0.],
                        [0., 1., 1., 1., 1., 1., 0.],
                        [0., 1., 1., 1., 1., 1., 0.],
                        [0., 1., 1., 1., 1., 1., 0.],
                        [0., 0., 0., 0., 0., 0., 0.]])).all

## 부울 인덱싱

**문제 1**

벡터가 아래와 같이 주어졌다.

In [ ]:
Z = np.arange(11)

3보다 크고 8보다 작은 값을 모두 음의 값으로 부호를 바꿔라.
단, 마스크를 활용하고 어레이와 스칼라 곱셈을 실행한다.

In [ ]:
mask = None
pass

아래 코드는 수정하지 마세요!!!

In [ ]:
assert (Z == np.array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])).all()

## 팬시 인덱싱

**문제 1**

2차원 어레이 `A`가 아래와 같이 주어졌다.

In [3]:
A = np.arange(25).reshape(5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

0행과 1행의 위치를 바꿔라.
단, 팬신 인덱싱을 이용한다.

In [6]:
A[(0,1)] = A[(1,0)]
print(A)

[[ 0  5  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


아래 코드는 수정하지 마세요!!!

In [5]:
assert (A == np.array([[ 5,  6,  7,  8,  9],
                        [ 0,  1,  2,  3,  4],
                        [10, 11, 12, 13, 14],
                        [15, 16, 17, 18, 19],
                        [20, 21, 22, 23, 24]])).all()

AssertionError: 

## 보간법

아래 코드는 너구리 얼굴 사진을 2차원 어레이로 불러온다.

In [ ]:
import scipy.misc
face = scipy.misc.face()/255 # 정규화 포함

In [ ]:
# 파이플롯
import matplotlib.pyplot as plt
# 도표 크기 지정
plt.rc('figure', figsize=(10, 6))

In [ ]:
plt.imshow(face)
plt.show()

**문제 1**

[이미지 크기 조정](file:///C:/Users/gslee/Documents/GitHub/datapy/jupyter-book/_build/html/numpy_2.html#id9)에서
사용한 보간법은 네 칸 중에서 대각선 상에 위치한 두 개의 픽셀에 대해서만 평균값을 계산한다.
이제 아래 그림이 보여주는 것처럼 네 칸 모두를 대상으로 픽셀 평균값을 계산하는 이미지 축소 함수 `resize_half()`를 정의하라.
단, 어레이 관련 연산, 메서드, 함수만 사용하며, `for` 반복문은 사용하지 않는다.

<img src="https://github.com/codingalzi/pydata/blob/master/notebooks/images/interpolation03.png?raw=true" style="width:150px;">

`resize_half()` 함수가 사용하는 매개변수의 기능과 반환값은 아래와 같이 지정돼야 한다.

* `imageName` 매개 변수: 이미지 어레이를 가리키는 변수. 이미지는 정규화가 되어 있어야 함.
* 반환값: 행과 열의 크기가 1/2로 줄어든 3차원 넘파이 어레이.

In [ ]:
def resize_half(imageName):
    pass
    return None

구현된 함수가 제대로 작동하는제 테스트하라.

In [ ]:
face_half = resize_half(face)

아래 코드는 수정하지 마세요!!!

In [ ]:
assert face_half.shape == (384, 512, 3)
assert np.allclose(face_half[0, 0], np.array([0.44901961, 0.41764706, 0.49019608]))

**문제 2**

**문제 1**에서 구현한 `resize_half()` 함수를 일반화하기 위해
이미지의 픽셀 수를 임의의 지정된 비율로 줄이는 함수 `resize_ratio()`를 선언하라.
사용되는 매개변수의 기능과 반환값은 아래와 같이 지정돼야 한다.

* `imageName` 매개 변수: 이미지 어레이를 가리키는 변수. 이미지는 정규화가 되어 있어야 함.
* `ratio` 매개 변수: 양의 정수. 키워드 인자로 사용되며 기본값은 2로 지정.
    기본값 2를 사용하면 `resize_half()` 함수와 동일하게 작동해야 함.
    일반적으로, n이 입력되면 n x n 모양의 픽셀 공간의 평균값을 이용해야 한다.
* 반환값: 행과 열의 크기가 1/n 로 줄어든 3차원 넘파이 어레이.
    n=2인 경우 **문제 1**의 경우와 동일하게 작동해야 한다.

**주의사항:** 
1. 행과 열의 크기를 n으로 나눴을 때 나머지로 남는 행과 열은 삭제한다.
1. n은 8 정도까지만 시험해 본다. 그보다 크면 원본 이미지에서 너무 많은 데이터를 잃어버릴 것이다.
1. 기본적으로 어레이 연산만 사용한다. `for` 반복문을 어레이의 각 항목의 값을 지정하는 데에 사용하지는 말아야 한다.

**힌트:**
`np.hsplit()` 함수와 `sum()` 메서드를 적절히 활용하면 `for` 반복문을 전혀 사용하지 않아도 된다.

In [ ]:
# pass와 None을 각각 적절한 코드와 값으로 대체해야 함.
def resize_ratio(imageName, ratio=2):
    pass
    return None

아래 코드는 수정하지 마세요!!!

In [ ]:
face_half_ratio = resize_ratio(face)

assert face_half_ratio.shape == (384, 512, 3)
assert np.allclose(face_half_ratio[0, 0], np.array([0.44901961, 0.41764706, 0.49019608]))

아래 코드는 수정하지 마세요!!!

In [ ]:
face_fourth = resize_ratio(face, 4)

assert face_fourth.shape == (192, 256, 3)